const passport = require("passport");
const mongoose = require("mongoose");
const GoogleStrategy = require("passport-google-oauth20").Strategy; // from node modules we only want
const keys = require("../config/keys");

// get the class of User from mongo
const User = mongoose.model("users");
passport.serializeUser((user, done) => {
  // 1st args in done is an error obj, if one exists
  done(null, user.id); // this is the id from mongo
});

// turn the id generated by passport to a mongoDB instance
passport.deserializeUser((userId, done) => {
  User.findById(userId).then((user) => {
    done(null, user);
  });
});

passport.use(
  new GoogleStrategy(
    {
      clientID: keys.googleClientID,
      clientSecret: keys.googleClientSecret,
      callbackURL: "/auth/google/callback",
    },
    async (accessToken, refreshToken, profile, done) => {
      // console.log(accessToken);
      // could be a possible instance
      User.findOne({ googleId: profile.id }).then((user) => {
        if (user) {
          done(null, user);
        } else {
          new User({ googleId: profile.id })
            .save()
            .then((user) => done(null, user));
        }
      });
    }
  ) // end of GoogleStrategy
); // end of passport.use()
